### PR TITLE
fixed: unhandled exception in sapi5.py, jaws.py and window_eyes.py

### PR DESCRIPTION
**Pull request by soundmud**
TypeError seems to replace pywintypes.com_error.
I kept pywintypes.com_error though, just in case.

### CODE REVIEW

**Comment by soundmud** [comment]
This unhandled exception will prevent Auto() from initializing correctly.

**Comment by soundmud** [comment]
I have received a similar bug report for jaws.py:

Traceback (most recent call last):
  File "accessible_output2\outputs\auto.py", line 13, in __init__
  File "accessible_output2\outputs\jaws.py", line 16, in __init__
  File "accessible_output2\outputs\__init__.py", line 10, in _load_com
  File "libloader\com.py", line 16, in load_com
  File "win32com\client\gencache.py", line 541, in EnsureDispatch
TypeError: This COM object can not automate the makepy process - please run makepy manually for this object

Actually, a few more files are probably concerned by the issue. I hope to add a commit to fix this soon.

This way, Auto() would eventually fallback to NDVA.

**Comment by ctoth** [comment]
Do you know under what case these TypeErrors are getting raised?

**Comment by soundmud** [comment]
All I have for now is the first part of the previous report:

Traceback (most recent call last):
  File "win32com\client\gencache.py", line 530, in EnsureDispatch
pywintypes.com_error: (-2147312566, 'Error loading type library/DLL.', None, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "accessible_output2\outputs\auto.py", line 13, in init
File "accessible_output2\outputs\jaws.py", line 16, in init
File "accessible_output2\outputs_init_.py", line 10, in _load_com
File "libloader\com.py", line 16, in load_com
File "win32com\client\gencache.py", line 541, in EnsureDispatch
TypeError: This COM object can not automate the makepy process - please run makepy manually for this object

**Pull request merged**
