### PR TITLE
Add ZDSR support

### PR DESCRIPTION
**Pull request by masonasons**

### CODE REVIEW

**Comment by ctoth** [comment]
Please update the documentation to mention this new output. Thank you for your work on this!

**Comment by masonasons** [comment]
@ctoth I've just updated the docs. :)

**Comment by ctoth** [comment]
Hi, I emailed a reply to this but apparently email replies aren't working. Please add this output to the README as well, and specify if it handles Speech or also Braille.

**Comment by masonasons** [comment]
Hi @Ctoth,

Done. :)

**Comment by ctoth** [comment]
@masonasons Thank you for your work on this!

**Pull request merged**
